### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by peter279k** [axelitus/php-base#4]
As title, is this project still maintained?

@axelitus, I want to contribute some codes and enhancement if possible.

**Comment by axelitus** [comment]
Hi @peter279k, sorry for the late response.

This project was first introduced as a package that I used personally as a base for my developments to scaffold some useful basic utilities.

I haven't really modified this in a while, as I'm working on a new approach of some of this functionality (as an example: scalar operations, but now as scalar extensible objects).

I'm leaning towards deprecating this package in favor of the ones being worked on:
https://github.com/norse-blue

Your contributions are certainly welcomed but I think your efforts would be of better use there.

That being said, for curiosity's sake, what is it that you wish to contribute to this project?

**Comment by peter279k** [comment]
> That being said, for curiosity's sake, what is it that you wish to contribute to this project?

Hi @axelitus, thanks for your reply. I think I want to contribute this project because I want to learn about advanced PHP functions development.

It's okay to focus on https://github.com/norse-blue and I think you can also let this repository be under archived mode.

And it can let other developers know that this repository will not be maintained anymore.

If someone need it, they will send message via e-mail to ask or fork it and continue maintaining again.

Hopefully you don't mind that I bother this inactive project you mention :).

**Comment by axelitus** [comment]
Not at all! I certainly need to mark this repo and package as no longer actively maintained. I haven't done that due to little time (though that is really an excuse).

I'll try to do so tomorrow, thanks again for your interest!
